CREATE OR REPLACE VIEW XXI.ICE_UNISTREAM_CLIENTS AS
SELECT
    -- PK
    CAST(NULL AS VARCHAR2(100))   AS CLIENT_ID,

    CAST(NULL AS VARCHAR2(3))     AS COUNTRY_OF_RESIDENCE,
    CAST(NULL AS VARCHAR2(100))   AS FIRST_NAME,
    CAST(NULL AS VARCHAR2(100))   AS LAST_NAME,
    CAST(NULL AS VARCHAR2(100))   AS MIDDLE_NAME,
    CAST(NULL AS VARCHAR2(10))    AS GENDER,
    CAST(NULL AS VARCHAR2(255))   AS BIRTH_PLACE,
    CAST(NULL AS TIMESTAMP)       AS BIRTH_DATE,

    CAST(NULL AS VARCHAR2(50))    AS PHONE_NUMBER,
    CAST(NULL AS VARCHAR2(20))    AS TAXPAYER_IDENTIFICATION_NUMBER,
    CAST(NULL AS VARCHAR2(50))    AS KAZ_ID,

    CAST(NULL AS VARCHAR2(500))   AS ADDRESS_STRING,
    CAST(NULL AS VARCHAR2(50))    AS APARTMENT,
    CAST(NULL AS VARCHAR2(50))    AS BUILDING,
    CAST(NULL AS VARCHAR2(100))   AS CITY,
    CAST(NULL AS VARCHAR2(3))     AS COUNTRY_CODE,
    CAST(NULL AS VARCHAR2(50))    AS HOUSE,
    CAST(NULL AS VARCHAR2(20))    AS POSTCODE,
    CAST(NULL AS VARCHAR2(100))   AS STATE,
    CAST(NULL AS VARCHAR2(255))   AS STREET,

    CAST(NULL AS VARCHAR2(50))    AS DOCUMENT_TYPE,
    CAST(NULL AS VARCHAR2(20))    AS DOCUMENT_SERIES,
    CAST(NULL AS VARCHAR2(20))    AS DOCUMENT_NUMBER,
    CAST(NULL AS VARCHAR2(255))   AS DOCUMENT_ISSUER,
    CAST(NULL AS VARCHAR2(20))    AS DOCUMENT_ISSUER_DEPARTMENT_CODE,
    CAST(NULL AS TIMESTAMP)       AS DOCUMENT_ISSUE_DATE,
    CAST(NULL AS TIMESTAMP)       AS DOCUMENT_EXPIRY_DATE,
    CAST(NULL AS VARCHAR2(10))    AS DOCUMENT_STATE,

    CAST(NULL AS TIMESTAMP)       AS CREATE_DATE
FROM
    DUAL;
/