SET DEFINE OFF
SPOOL runme.log

SELECT USER || '@' || GLOBAL_NAME || ' ' || TO_CHAR (SYSDATE, 'DD.MM.YYYY HH24:MI:SS') "Script processed on"
       FROM GLOBAL_NAME
/

PROMPT 01_ISIMPLE_OV_UNIS_CUS.sql
@@01_ISIMPLE_OV_UNIS_CUS.sql
SHOW ERRORS

PROMPT 02_ISIMPLE_OV_UNIS_CLIENTS.sql
@@02_ISIMPLE_OV_UNIS_CLIENTS.sql
SHOW ERRORS

                      
SPOOL OFF
